/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Master.Form_User;
import Master.Form_Suplier;
import Master.Form_Barang;
import Master.Form_Kategori;
import Master.Form_Pelanggan;
import config.SyncService;
import view.Form_Login_old;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Lenovo
 */
public class Menu_Utama extends javax.swing.JFrame {

    /** A BoxLayout panel that tracks the JScrollPane viewport's width instead of
     *  the (buggy, MAX_VALUE-sized) width BoxLayout would otherwise compute for
     *  children whose maximum width is Integer.MAX_VALUE. */
    private static class ScrollableMenuPanel extends javax.swing.JPanel implements javax.swing.Scrollable {
        public java.awt.Dimension getPreferredScrollableViewportSize() {
            return getPreferredSize();
        }
        public int getScrollableUnitIncrement(java.awt.Rectangle visibleRect, int orientation, int direction) {
            return 16;
        }
        public int getScrollableBlockIncrement(java.awt.Rectangle visibleRect, int orientation, int direction) {
            return visibleRect.height;
        }
        public boolean getScrollableTracksViewportWidth() {
            return true;
        }
        public boolean getScrollableTracksViewportHeight() {
            return false;
        }
    }

    /**
     * Creates new form Menu_Utama
     */
    public static boolean tutup = false;

    public Menu_Utama(String nama, String level) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        String levelText;
        if ("PEMILIK".equals(level) || "Owner".equals(level)) {
            levelText = "Owner";
        } else if ("KARYAWAN".equals(level) || "Employee".equals(level)) {
            levelText = "Employee";
        } else {
            levelText = level;
        }
        lb_nama.setText(nama);
        lb_level.setText(levelText);
        lb_signedInValue.setText(nama + "  ·  " + levelText);
        fitSignedInHeader();
        // Layout may run before fonts/metrics settle — resize again on the EDT.
        javax.swing.SwingUtilities.invokeLater(this::fitSignedInHeader);
        execute();
        Date();
        SyncService.getInstance().start();
        startSyncIndicatorTimer();
    }

    private void Date() {
        Date TanggalSekarang = new Date();
        SimpleDateFormat TanggalWaktu = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = TanggalWaktu.format(TanggalSekarang);
        lb_tanggal.setText(tanggal);
    }

    private void startSyncIndicatorTimer() {
        refreshSyncIndicator();
        syncIndicatorTimer = new Timer(30_000, e -> refreshSyncIndicator());
        syncIndicatorTimer.setRepeats(true);
        syncIndicatorTimer.start();
    }

    private void refreshSyncIndicator() {
        if (lb_syncDot == null || lb_syncLabel == null) {
            return;
        }
        try {
            SyncService.StatusSnapshot snap = SyncService.getInstance().getStatusSnapshot();
            Color dot;
            switch (snap.indicator) {
                case SYNCED:
                    dot = new Color(0x2E7D32);
                    break;
                case PENDING:
                    dot = new Color(0xF9A825);
                    break;
                case DISABLED:
                    dot = new Color(0x9B9B98);
                    break;
                case OFFLINE:
                default:
                    dot = new Color(0xC62828);
                    break;
            }
            lb_syncDot.setForeground(dot);
            lb_syncLabel.setText(snap.label);
        } catch (Exception e) {
            lb_syncDot.setForeground(new Color(0xC62828));
            lb_syncLabel.setText("Offline");
        }
    }

    JButton btnNewButton = new JButton("Logout");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_navbar = new javax.swing.JPanel();
        lb_tanggal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new ScrollableMenuPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_level = new javax.swing.JLabel();
        lb_nama = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        // Extra chrome components for the editorial admin look (added on top
        // of the generated fields above; not part of the NetBeans-managed set).
        lb_dateCaption = new javax.swing.JLabel();
        lb_signedInCaption = new javax.swing.JLabel();
        lb_signedInValue = new FullTextLabel();
        panel_logout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        // ---- Sidebar (full-height): brand + nav + logout ----
        panel_sidebar.setBackground(Main.UITheme.NAV_BG);
        panel_sidebar.setPreferredSize(new java.awt.Dimension(248, 432));
        panel_sidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, Main.UITheme.GRID_LINE));
        panel_sidebar.setLayout(new java.awt.BorderLayout());

        jLabel2.setOpaque(false);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(44, 44));
        jLabel2.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel2.setMaximumSize(new java.awt.Dimension(44, 44));
        ShopBranding.applyLogoLabel(jLabel2, 44);

        jLabel1.setText("<html><span style='font-size:12px;color:#1A1A1A;'><b>KHALID FARMS</b></span><br>"
                + "<span style='font-size:9px;color:#9B9B98;letter-spacing:0.5px;'>BAHRIA TOWN LAHORE</span></html>");

        javax.swing.JPanel brandHeader = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 14, 0));
        brandHeader.setBackground(Main.UITheme.NAV_BG);
        brandHeader.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Main.UITheme.NAV_RULE),
            javax.swing.BorderFactory.createEmptyBorder(20, 24, 20, 16)));
        brandHeader.add(jLabel2);
        brandHeader.add(jLabel1);
        panel_sidebar.add(brandHeader, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBackground(Main.UITheme.NAV_BG);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pn_menu.setBackground(Main.UITheme.NAV_BG);
        pn_menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 0, 8, 0));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);
        panel_sidebar.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panel_logout.setBackground(Main.UITheme.NAV_BG);
        panel_logout.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, Main.UITheme.NAV_RULE),
            javax.swing.BorderFactory.createEmptyBorder(18, 24, 20, 16)));
        panel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        javax.swing.JLabel lb_logout = new javax.swing.JLabel("LOG OUT  →");
        lb_logout.setFont(Main.UITheme.FONT_BOLD.deriveFont(11f));
        lb_logout.setForeground(Main.UITheme.ACCENT);
        panel_logout.setLayout(new java.awt.BorderLayout());
        panel_logout.add(lb_logout, java.awt.BorderLayout.WEST);
        panel_sidebar.add(panel_logout, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panel_sidebar, java.awt.BorderLayout.LINE_START);

        // ---- Right column: top meta bar + page content ----
        javax.swing.JPanel rightColumn = new javax.swing.JPanel(new java.awt.BorderLayout());
        rightColumn.setBackground(Main.UITheme.PAGE_BG);

        panel_navbar.setBackground(Main.UITheme.SURFACE);
        panel_navbar.setPreferredSize(new java.awt.Dimension(871, 64));
        panel_navbar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Main.UITheme.GRID_LINE));
        panel_navbar.setLayout(new java.awt.BorderLayout());

        lb_dateCaption.setFont(Main.UITheme.FONT_CAPTION);
        lb_dateCaption.setForeground(Main.UITheme.TEXT_CAPTION);
        lb_dateCaption.setText("DATE");

        lb_tanggal.setFont(Main.UITheme.FONT_BOLD.deriveFont(13f));
        lb_tanggal.setForeground(Main.UITheme.TEXT_PRIMARY);
        lb_tanggal.setText("Date ");

        lb_signedInCaption.setFont(Main.UITheme.FONT_CAPTION);
        lb_signedInCaption.setForeground(Main.UITheme.TEXT_CAPTION);
        lb_signedInCaption.setText("SIGNED IN");

        lb_signedInValue.setFont(Main.UITheme.FONT_BOLD.deriveFont(13f));
        lb_signedInValue.setForeground(Main.UITheme.TEXT_PRIMARY);
        lb_signedInValue.setText("—");

        jButton1.setText("Profile");
        jButton1.setFont(Main.UITheme.FONT_BOLD.deriveFont(12f));
        jButton1.setBackground(Main.UITheme.SURFACE);
        jButton1.setForeground(Main.UITheme.TEXT_PRIMARY);
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 28, 0, 28));
        jButton1.setFocusPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.JPanel dateCell = headerMetaCell(lb_dateCaption, lb_tanggal);
        headerSignedInCell = headerMetaCell(lb_signedInCaption, lb_signedInValue);

        lb_syncCaption = new javax.swing.JLabel();
        lb_syncCaption.setFont(Main.UITheme.FONT_CAPTION);
        lb_syncCaption.setForeground(Main.UITheme.TEXT_CAPTION);
        lb_syncCaption.setText("SYNC");
        lb_syncDot = new JLabel("●");
        lb_syncDot.setFont(Main.UITheme.FONT_BOLD.deriveFont(12f));
        lb_syncDot.setForeground(new Color(0x9B9B98));
        lb_syncLabel = new JLabel("—");
        lb_syncLabel.setFont(Main.UITheme.FONT_BOLD.deriveFont(13f));
        lb_syncLabel.setForeground(Main.UITheme.TEXT_PRIMARY);
        javax.swing.JPanel syncValueRow = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT, 6, 0));
        syncValueRow.setOpaque(false);
        syncValueRow.add(lb_syncDot);
        syncValueRow.add(lb_syncLabel);
        headerSyncCell = headerMetaCell(lb_syncCaption, syncValueRow);

        javax.swing.JPanel profileCell = new javax.swing.JPanel(new java.awt.BorderLayout());
        profileCell.setBackground(Main.UITheme.SURFACE);
        profileCell.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, Main.UITheme.GRID_LINE));
        profileCell.add(jButton1, java.awt.BorderLayout.CENTER);
        profileCell.setPreferredSize(new java.awt.Dimension(
                Math.max(110, jButton1.getPreferredSize().width + 4), 64));
        profileCell.setMinimumSize(profileCell.getPreferredSize());
        profileCell.setMaximumSize(new java.awt.Dimension(
                profileCell.getPreferredSize().width, Integer.MAX_VALUE));

        // FlowLayout keeps each cell at its preferred width (no equal-column squeeze).
        javax.swing.JPanel metaRow = new javax.swing.JPanel(
                new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));
        metaRow.setOpaque(false);
        metaRow.add(dateCell);
        metaRow.add(headerSyncCell);
        metaRow.add(headerSignedInCell);
        metaRow.add(profileCell);
        panel_navbar.add(metaRow, java.awt.BorderLayout.EAST);

        javax.swing.JPanel navbarSpacer = new javax.swing.JPanel();
        navbarSpacer.setOpaque(false);
        panel_navbar.add(navbarSpacer, java.awt.BorderLayout.CENTER);

        rightColumn.add(panel_navbar, java.awt.BorderLayout.NORTH);

        panel_content.setBackground(Main.UITheme.PAGE_BG);

        pn_utama.setBackground(Main.UITheme.PAGE_BG);
        pn_utama.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
        panel_content.setLayout(panel_contentLayout);
        panel_contentLayout.setHorizontalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        panel_contentLayout.setVerticalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        rightColumn.add(panel_content, java.awt.BorderLayout.CENTER);
        getContentPane().add(rightColumn, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(896, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (user.getJenisUser().equals("Owner") || user.getJenisUser().equals("PEMILIK")) {
            pn_utama.add(new Form_DasbordPemilik());
            pn_utama.repaint();
            pn_utama.revalidate();
        } else if (user.getJenisUser().equals("Employee") || user.getJenisUser().equals("KARYAWAN")) {
            // Staff only has Sell — land there immediately.
            pn_utama.add(new Form_Penjualan());
            pn_utama.repaint();
            pn_utama.revalidate();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Form_Akun().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Modern flat look and feel (FlatLaf) — replaces the old Nimbus LaF. */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        Main.UITheme.apply();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama("Name", "level").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_level;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_tanggal;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    // Extra chrome fields for the editorial admin look.
    private javax.swing.JLabel lb_dateCaption;
    private javax.swing.JLabel lb_signedInCaption;
    private javax.swing.JLabel lb_signedInValue;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JPanel headerSignedInCell;
    private javax.swing.JLabel lb_syncCaption;
    private javax.swing.JLabel lb_syncDot;
    private javax.swing.JLabel lb_syncLabel;
    private javax.swing.JPanel headerSyncCell;
    private Timer syncIndicatorTimer;

    private final List<MenuItem> navItems = new ArrayList<>();

    /**
     * Label that never ellipsizes — FlatLaf/Swing's layoutCompoundLabel was
     * clipping "admin · Owner" to "admin · Ow..." when the cell was narrow.
     */
    private static final class FullTextLabel extends javax.swing.JLabel {
        FullTextLabel() {
            setOpaque(false);
        }

        @Override
        public java.awt.Dimension getPreferredSize() {
            java.awt.Font font = getFont();
            if (font == null) {
                return super.getPreferredSize();
            }
            String text = getText() == null ? "" : getText();
            java.awt.FontMetrics fm = getFontMetrics(font);
            java.awt.Insets in = getInsets();
            int padX = (in == null ? 0 : in.left + in.right);
            int padY = (in == null ? 0 : in.top + in.bottom);
            return new java.awt.Dimension(
                    fm.stringWidth(text) + padX + 2,
                    Math.max(fm.getHeight() + padY, 16));
        }

        @Override
        public java.awt.Dimension getMinimumSize() {
            return getPreferredSize();
        }

        @Override
        public java.awt.Dimension getMaximumSize() {
            return getPreferredSize();
        }

        @Override
        protected void paintComponent(java.awt.Graphics g) {
            if (isOpaque()) {
                g.setColor(getBackground());
                g.fillRect(0, 0, getWidth(), getHeight());
            }
            String text = getText();
            if (text == null || text.isEmpty()) {
                return;
            }
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            try {
                g2.setRenderingHint(java.awt.RenderingHints.KEY_TEXT_ANTIALIASING,
                        java.awt.RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g2.setFont(getFont());
                g2.setColor(getForeground());
                java.awt.FontMetrics fm = g2.getFontMetrics();
                java.awt.Insets in = getInsets();
                int x = in == null ? 0 : in.left;
                int y = (in == null ? 0 : in.top) + fm.getAscent()
                        + Math.max(0, (getHeight() - fm.getHeight()) / 2);
                g2.drawString(text, x, y);
            } finally {
                g2.dispose();
            }
        }
    }

    /** Bordered meta cell used in the top bar (DATE / SIGNED IN / SYNC). */
    private javax.swing.JPanel headerMetaCell(javax.swing.JLabel caption, java.awt.Component value) {
        javax.swing.JPanel cell = new javax.swing.JPanel(new java.awt.BorderLayout(0, 2));
        cell.setBackground(Main.UITheme.SURFACE);
        cell.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, Main.UITheme.GRID_LINE),
            javax.swing.BorderFactory.createEmptyBorder(12, 22, 12, 28)));
        caption.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        if (value instanceof javax.swing.JLabel) {
            ((javax.swing.JLabel) value).setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        }
        cell.add(caption, java.awt.BorderLayout.NORTH);
        cell.add(value, java.awt.BorderLayout.CENTER);
        return cell;
    }

    /** Resize SIGNED IN cell so the full username · role string is visible. */
    private void fitSignedInHeader() {
        if (lb_signedInValue == null || headerSignedInCell == null) {
            return;
        }
        String text = lb_signedInValue.getText() == null ? "" : lb_signedInValue.getText();
        java.awt.Font font = lb_signedInValue.getFont();
        if (font == null) {
            font = Main.UITheme.FONT_BOLD.deriveFont(13f);
            lb_signedInValue.setFont(font);
        }
        int textW = lb_signedInValue.getFontMetrics(font).stringWidth(text);
        int capW = 0;
        if (lb_signedInCaption.getFont() != null && lb_signedInCaption.getText() != null) {
            capW = lb_signedInCaption.getFontMetrics(lb_signedInCaption.getFont())
                    .stringWidth(lb_signedInCaption.getText());
        }
        // Explicit padding (border may not report insets until displayable).
        int pad = 22 + 28 + 16;
        int width = Math.max(220, Math.max(textW, capW) + pad);
        java.awt.Dimension size = new java.awt.Dimension(width, 64);
        headerSignedInCell.setPreferredSize(size);
        headerSignedInCell.setMinimumSize(size);
        headerSignedInCell.setMaximumSize(size);
        if (panel_navbar != null) {
            panel_navbar.revalidate();
            panel_navbar.repaint();
        }
    }

    /** Builds a numbered, clickable sidebar row that swaps the content panel when clicked. */
    private MenuItem navItem(int index, String menuName, java.util.function.Supplier<JPanel> pageSupplier) {
        final MenuItem[] holder = new MenuItem[1];
        MenuItem item = new MenuItem(index, menuName, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selectNavItem(holder[0]);
                pn_utama.removeAll();
                pn_utama.add(pageSupplier.get());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        holder[0] = item;
        navItems.add(item);
        pn_menu.add(item);
        return item;
    }

    private void selectNavItem(MenuItem selected) {
        for (MenuItem m : navItems) {
            m.setSelected(m == selected);
        }
    }

    /** Open a sidebar page by its menu label (e.g. "Sell", "Restock", "Reports"). */
    public void openPage(String menuName) {
        if (menuName == null) {
            return;
        }
        for (MenuItem m : navItems) {
            if (!m.isHeader() && menuName.equalsIgnoreCase(m.getMenuName())) {
                m.activate();
                return;
            }
        }
    }

    private void execute() {
        boolean isOwner = user.getJenisUser().equals("Owner") || user.getJenisUser().equals("PEMILIK");
        int i = 1;
        MenuItem home;

        if (isOwner) {
            pn_menu.add(new MenuItem("Overview", false));
            home = navItem(i++, "Dashboard", () -> new Form_DasbordPemilik());

            pn_menu.add(new MenuItem("Master Data", true));
            navItem(i++, "Products", () -> new Form_Barang());
            navItem(i++, "Categories", () -> new Form_Kategori());
            navItem(i++, "Customers", () -> new Form_Pelanggan());
            navItem(i++, "Suppliers", () -> new Form_Suplier());
            navItem(i++, "Users", () -> {
                try {
                    return new Form_User();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
                    return new JPanel();
                }
            });

            pn_menu.add(new MenuItem("Transactions", true));
            navItem(i++, "Sell", () -> new Form_Penjualan());
            navItem(i++, "Restock", () -> new Form_Pembelian());
            navItem(i++, "Expenses", () -> new Form_Pengeluaran());
            navItem(i++, "Reports", () -> new Form_ReportPemilik());

            pn_menu.add(new MenuItem("Settings", true));
            navItem(i++, "Invoice", () -> new Form_Pengaturan());
        } else {
            // Staff: Sell, Customers, and today's sales.
            pn_menu.add(new MenuItem("Register", false));
            home = navItem(i++, "Sell", () -> new Form_Penjualan());
            navItem(i++, "Customers", () -> new Form_Pelanggan());
            navItem(i++, "Today's sales", () -> new Form_ReportKaryawan());
        }

        pn_menu.revalidate();

        selectNavItem(home);

        panel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int a = JOptionPane.showConfirmDialog(null, "Are you sure?", "Select", JOptionPane.YES_NO_OPTION);
                if (a == JOptionPane.YES_OPTION) {
                    dispose();
                    Form_Login_old obj = null;
                    try {
                        obj = new Form_Login_old();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    obj.setVisible(true);
                }
            }
        });
    }

}
